name=embedded-gcov-lib
version=0.1.0
author=Ken Peters
maintainer=Your Name or Email
sentence=A library for enabling code coverage on embedded systems using gcov.
paragraph=This library provides a simple interface to enable code coverage on your embedded projects using gcov. It supports Arduino and other platforms.
category=Other
url=https://github.com/zanac73/embedded-gcov-lib
architectures=*
depends=
