[platformio]
name = Test Coverage Demo
description = simple PlatformIO project to demonstrate how test-coverage works for unitTesting


; ------------------------------------------------
; --- Settings common to all environment       ---
; ------------------------------------------------

[env]

; ------------------------------------------------
; --- Generic : for HW-independent unit testing ---
; ------------------------------------------------

[env:native]
platform = native
lib_ldf_mode = deep
build_flags = 
    -D unitTesting
    -lgcov
    --coverage
    -fprofile-abs-path

debug_build_flags = 
    -D unitTesting
    -Og
    -ggdb

test_framework = unity
test_filter = test_*
debug_test = test_key

check_src_filters =     
    lib/*
    test/*

[env:esp32]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
build_flags = 
    -fprofile-arcs
    -ftest-coverage
lib_deps = 
    https://github.com/zanac73/embedded-gcov-lib
